version: '3'

services:
  animal-collector:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: animal-collector
    restart: always
    tty: true
    expose:
      - 6000
    ports:
      - 6000:6000
    volumes:
      - ../:/app
