version: '3'

services:
  animal-collector:
    image: continuumio/anaconda3:latest
    container_name: animal-collector
    restart: always
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ../:/app
    # command: "pip3 install -r requirements.txt"
